### ISSUE TITLE
Support for VS2013 Update 5

### ISSUE THREAD

**Issue by cigano** [processedbeets/ASP.NET-MVC-Scaffolding#1]
As you mentioned in your README, yes, there's a problem trying to install your version of MvcScaffolding in Visual Studio 2013 projects. 

I can work on the problem, but I need to know in which place I need to start. 

The errors are basically in portuguese, but the exception codes are showed.

The error is:

PM> Install-Package MvcScaffolding.VS2015
Attempting to resolve dependency 'T4Scaffolding.VS2015'.
Attempting to resolve dependency 'T4Scaffolding.Core.VS2015'.
Attempting to resolve dependency 'EntityFramework (≥ 4.1.10311.0)'.
Installing 'T4Scaffolding.Core.VS2015 1.0.1'.
Successfully installed 'T4Scaffolding.Core.VS2015 1.0.1'.
Set-DefaultScaffolder : Operação não disponível (Exception from HRESULT: 0x800401E3 (MK_E_UNAVAILABLE))
At C:\users\lsanches\documents\visual studio 2013\Projects\TesteScaffolding\packages\T4Scaffolding.Core.VS2015.1.0.1\tools\init.ps1:50 char:9
-         Set-DefaultScaffolder -Name CustomTemplate -Scaffolder T4Scaffolding.Cus ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Set-DefaultScaffolder], COMException
  - FullyQualifiedErrorId : T4Scaffolding.Cmdlets.SetDefaultScaffolderCmdlet

Set-DefaultScaffolder : Operação não disponível (Exception from HRESULT: 0x800401E3 (MK_E_UNAVAILABLE))
At C:\users\lsanches\documents\visual studio 2013\Projects\TesteScaffolding\packages\T4Scaffolding.Core.VS2015.1.0.1\tools\init.ps1:51 char:9
-         Set-DefaultScaffolder -Name CustomScaffolder -Scaffolder T4Scaffolding.C ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Set-DefaultScaffolder], COMException
  - FullyQualifiedErrorId : T4Scaffolding.Cmdlets.SetDefaultScaffolderCmdlet

Installing 'T4Scaffolding.VS2015 1.0.8'.
Successfully installed 'T4Scaffolding.VS2015 1.0.8'.
Set-DefaultScaffolder : Operação não disponível (Exception from HRESULT: 0x800401E3 (MK_E_UNAVAILABLE))
At C:\users\lsanches\documents\visual studio 2013\Projects\TesteScaffolding\packages\T4Scaffolding.VS2015.1.0.8\tools\init.ps1:6 char:1
- Set-DefaultScaffolder -Name DbContext -Scaffolder T4Scaffolding.EFDbContext -Sol ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Set-DefaultScaffolder], COMException
  - FullyQualifiedErrorId : T4Scaffolding.Cmdlets.SetDefaultScaffolderCmdlet

Set-DefaultScaffolder : Operação não disponível (Exception from HRESULT: 0x800401E3 (MK_E_UNAVAILABLE))
At C:\users\lsanches\documents\visual studio 2013\Projects\TesteScaffolding\packages\T4Scaffolding.VS2015.1.0.8\tools\init.ps1:7 char:1
- Set-DefaultScaffolder -Name Repository -Scaffolder T4Scaffolding.EFRepository -S ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Set-DefaultScaffolder], COMException
  - FullyQualifiedErrorId : T4Scaffolding.Cmdlets.SetDefaultScaffolderCmdlet

Installing 'MvcScaffolding.VS2015 1.0.10'.
Successfully installed 'MvcScaffolding.VS2015 1.0.10'.
Set-DefaultScaffolder : Operação não disponível (Exception from HRESULT: 0x800401E3 (MK_E_UNAVAILABLE))
At C:\users\lsanches\documents\visual studio 2013\Projects\TesteScaffolding\packages\MvcScaffolding.VS2015.1.0.10\tools\init.ps1:48 char:1
- Set-DefaultScaffolder -Name Controller -Scaffolder MvcScaffolding.Controller -So ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Set-DefaultScaffolder], COMException
  - FullyQualifiedErrorId : T4Scaffolding.Cmdlets.SetDefaultScaffolderCmdlet

Set-DefaultScaffolder : Operação não disponível (Exception from HRESULT: 0x800401E3 (MK_E_UNAVAILABLE))
At C:\users\lsanches\documents\visual studio 2013\Projects\TesteScaffolding\packages\MvcScaffolding.VS2015.1.0.10\tools\init.ps1:49 char:1
- Set-DefaultScaffolder -Name Views -Scaffolder MvcScaffolding.Views -SolutionWide ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Set-DefaultScaffolder], COMException
  - FullyQualifiedErrorId : T4Scaffolding.Cmdlets.SetDefaultScaffolderCmdlet

Set-DefaultScaffolder : Operação não disponível (Exception from HRESULT: 0x800401E3 (MK_E_UNAVAILABLE))
At C:\users\lsanches\documents\visual studio 2013\Projects\TesteScaffolding\packages\MvcScaffolding.VS2015.1.0.10\tools\init.ps1:50 char:1
- Set-DefaultScaffolder -Name Action -Scaffolder MvcScaffolding.Action -SolutionWi ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Set-DefaultScaffolder], COMException
  - FullyQualifiedErrorId : T4Scaffolding.Cmdlets.SetDefaultScaffolderCmdlet

Set-DefaultScaffolder : Operação não disponível (Exception from HRESULT: 0x800401E3 (MK_E_UNAVAILABLE))
At C:\users\lsanches\documents\visual studio 2013\Projects\TesteScaffolding\packages\MvcScaffolding.VS2015.1.0.10\tools\init.ps1:51 char:1
- Set-DefaultScaffolder -Name UnitTest -Scaffolder MvcScaffolding.ActionUnitTest - ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Set-DefaultScaffolder], COMException
  - FullyQualifiedErrorId : T4Scaffolding.Cmdlets.SetDefaultScaffolderCmdlet

Set-DefaultScaffolder : Operação não disponível (Exception from HRESULT: 0x800401E3 (MK_E_UNAVAILABLE))
At C:\users\lsanches\documents\visual studio 2013\Projects\TesteScaffolding\packages\MvcScaffolding.VS2015.1.0.10\tools\init.ps1:55 char:1
- Set-DefaultScaffolder -Name View -Scaffolder $viewScaffolder -SolutionWide -DoNo ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Set-DefaultScaffolder], COMException
  - FullyQualifiedErrorId : T4Scaffolding.Cmdlets.SetDefaultScaffolderCmdlet

Adding 'T4Scaffolding.Core.VS2015 1.0.1' to TesteScaffolding.
Successfully added 'T4Scaffolding.Core.VS2015 1.0.1' to TesteScaffolding.
Adding 'T4Scaffolding.VS2015 1.0.8' to TesteScaffolding.
Successfully added 'T4Scaffolding.VS2015 1.0.8' to TesteScaffolding.
Adding 'MvcScaffolding.VS2015 1.0.10' to TesteScaffolding.
Successfully added 'MvcScaffolding.VS2015 1.0.10' to TesteScaffolding.

PM> Set-DefaultScaffolder -Name View -Scaffolder "MvcScaffolding.RazorView" -SolutionWide -DoNotOverwriteExistingSetting
Set-DefaultScaffolder : Operação não disponível (Exception from HRESULT: 0x800401E3 (MK_E_UNAVAILABLE))
At line:1 char:1
- Set-DefaultScaffolder -Name View -Scaffolder "MvcScaffolding.RazorView" -Solutio ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Set-DefaultScaffolder], COMException
  - FullyQualifiedErrorId : T4Scaffolding.Cmdlets.SetDefaultScaffolderCmdlet

PM> Set-DefaultScaffolder
cmdlet Set-DefaultScaffolder at command pipeline position 1
Supply values for the following parameters:
Name: 
Scaffolder: 
Set-DefaultScaffolder : Cannot bind argument to parameter 'Name' because it is an empty string.
At line:1 char:1
- Set-DefaultScaffolder
- ~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidData: (:) [Set-DefaultScaffolder], ParameterBindingValidationException
  - FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,T4Scaffolding.Cmdlets.SetDefaultScaffolderCmdlet

PM> Get-DefaultScaffolder
Get-DefaultScaffolder : Operação não disponível (Exception from HRESULT: 0x800401E3 (MK_E_UNAVAILABLE))
At line:1 char:1
- Get-DefaultScaffolder
- ~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Get-DefaultScaffolder], COMException
  - FullyQualifiedErrorId : T4Scaffolding.Cmdlets.GetDefaultScaffolderCmdlet

**Comment by processedbeets** [comment]
Hi,

Thanks for getting in touch. It looks like the errors may be occurring in the same location as with the VS2015 fix. Both the Set-DefaultScaffolder & Get-DefaultScaffolder eventually call down to a constructor ScaffoldingSolutionManager. It is within here that there is an attempt to set the local _dte variable. The original code simply tried to set the variable like so:

_dte= (DTE)Package.GetGlobalService(typeof(DTE)) 

However, I added a null-coalescing operator (??) and then made an attempt to capture the active object currently running "visualstudio.dte":

_dte= (DTE)Package.GetGlobalService(typeof(DTE)) ?? (DTE)Marshal.GetActiveObject("visualstudio.dte");

I think your first port of call should be looking here. I would suggest opening up Visual Studio 2013, then opening Windows Powershell ISE and running the following:

'[Runtime.InteropServices.Marshal]::GetActiveObject('visualstudio.dte')' 

... without the surrounding inverted commas.

If this doesn't return an object, then it would suggest you need an alternative to 'visualstudio.dte', that can correctly discover VS 2013 Update 5 DTE. I could maybe take a look at this, this week, but will first need to setup a VM with VS 2013 Update 5. Let me know how you get on first.

Many thanks,
David.

**Comment by cigano** [comment]
Hello David, 

I performed the test you suggested and this was the result:

PM> [Runtime.InteropServices.Marshal]::GetActiveObject('visualstudio.dte')

Name                   : Microsoft Visual Studio
FileName               : C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe
Version                : 14.0
CommandBars            : System.__ComObject
Windows                : System.__ComObject
Events                 : System.__ComObject
AddIns                 : 
MainWindow             : System.__ComObject
ActiveWindow           : System.__ComObject
DisplayMode            : 2
Solution               : System.__ComObject
Commands               : System.__ComObject
SelectedItems          : System.__ComObject
CommandLineArguments   : 
DTE                    : System.__ComObject
LocaleID               : 1033
WindowConfigurations   : System.__ComObject
Documents              : System.__ComObject
ActiveDocument         : 
Globals                : System.__ComObject
StatusBar              : System.__ComObject
FullName               : C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe
UserControl            : True
ObjectExtenders        : System.__ComObject
Find                   : System.__ComObject
Mode                   : 1
ItemOperations         : System.__ComObject
UndoContext            : System.__ComObject
Macros                 : 
ActiveSolutionProjects : {}
MacrosIDE              : 
RegistryRoot           : Software\Microsoft\VisualStudio\14.0
Application            : System.__ComObject
ContextAttributes      : System.__ComObject
SourceControl          : System.__ComObject
SuppressUI             : True
Debugger               : System.__ComObject
Edition                : Community

Apparently, as I also installed Visual Studio 2015 (and your package worked perfectly on it), the environment is considering the DTE from Visual Studio 2015. 

However, this test was made with Visual Studio 2015 open. When I close it and run the same command only with Visual Studio 2013 open, I get this error:

PM> [Runtime.InteropServices.Marshal]::GetActiveObject('visualstudio.dte')
Exception calling "GetActiveObject" with "1" argument(s): "Operação não disponível (Exception from HRESULT: 0x800401E3 (MK_E_UNAVAILABLE))"
At line:1 char:1
- [Runtime.InteropServices.Marshal]::GetActiveObject('visualstudio.dte')
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
  - FullyQualifiedErrorId : COMException

**Comment by cigano** [comment]
Another test I've made, following [this post](https://msdn.microsoft.com/en-us/library/68shb4dw.aspx), worked:

PM> [Runtime.InteropServices.Marshal]::GetActiveObject('visualstudio.dte.12.0')

Name                   : Microsoft Visual Studio
FileName               : C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\devenv.exe
Version                : 12.0
CommandBars            : System.__ComObject
Windows                : System.__ComObject
Events                 : System.__ComObject
AddIns                 : System.__ComObject
MainWindow             : System.__ComObject
ActiveWindow           : System.__ComObject
DisplayMode            : 2
Solution               : System.__ComObject
Commands               : System.__ComObject
SelectedItems          : System.__ComObject
CommandLineArguments   : 
DTE                    : System.__ComObject
LocaleID               : 1033
WindowConfigurations   : System.__ComObject
Documents              : System.__ComObject
ActiveDocument         : System.__ComObject
Globals                : System.__ComObject
StatusBar              : System.__ComObject
FullName               : C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\devenv.exe
UserControl            : True
ObjectExtenders        : System.__ComObject
Find                   : System.__ComObject
Mode                   : 1
ItemOperations         : System.__ComObject
UndoContext            : System.__ComObject
Macros                 : System.__ComObject
ActiveSolutionProjects : {System.__ComObject}
MacrosIDE              : 
RegistryRoot           : Software\Microsoft\VisualStudio\12.0
Application            : System.__ComObject
ContextAttributes      : System.__ComObject
SourceControl          : System.__ComObject
SuppressUI             : True
Debugger               : System.__ComObject
Edition                : Professional

**Comment by processedbeets** [comment]
Great. That tells us the problem is in obtaining a handle to the DTE object of Visual Studio 2013. 

One thing you may wish to try is '[Runtime.InteropServices.Marshal]::GetActiveObject('visualstudio.dte.12.0')'

that's VS2013. See if it returns.

**Comment by processedbeets** [comment]
Ha, you beat me to it. Yes, I deliberately didn't specify a version in mine as I'd hoped visualstudio.dte would capture 2013 & 2015. Clearly it only works on VS2015.

OK, so leave it with me, I'll try adding in a check first for 2013, then if that fails, we can default to 2015.

Thanks for checking that.

**Comment by cigano** [comment]
Okay, works. Now let's change the code a bit. My suggestion is:

```
    public ScaffoldingSolutionManager(string defaultProjectName)
    {
        _defaultProjectName = defaultProjectName;
        _dte= ((DTE)Package.GetGlobalService(typeof(DTE)) ?? (DTE)Marshal.GetActiveObject("visualstudio.dte")) ?? (DTE)Marshal.GetActiveObject("visualstudio.dte.12.0");
        if (_dte == null) throw new InvalidOperationException("XXX Cannot get an instance of EnvDTE.DTE");
    }
```

How can I test this code?

**Comment by processedbeets** [comment]
great, OK, I'll add that in and check it in. 

I'll upload the package and alert you once it's done.

Thanks.

**Comment by processedbeets** [comment]
I've now uploaded a fix to the source and new versions of the NuGet packages. The new versions are as follows:
- T4Scaffolding.Core v.1.0.2
- T4Scaffolding v.1.0.9
- MvcScaffolding v.1.0.11

Let me know how you get on.

**Comment by cigano** [comment]
Hi David, 

Well, I think now the problem should be in another place. I've performed an `Update-Database` command and this error remains the same:

Set-DefaultScaffolder : Operação não disponível (Exception from HRESULT: 0x800401E3 (MK_E_UNAVAILABLE))
At C:\Users\lsanches\Documents\Visual Studio 2013\Projects\TesteScaffolding\packages\T4Scaffolding.Core.VS2015.1.0.2\tools\init.ps1:51 char:9
-         Set-DefaultScaffolder -Name CustomScaffolder -Scaffolder T4Scaffolding.C ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Set-DefaultScaffolder], COMException
  - FullyQualifiedErrorId : T4Scaffolding.Cmdlets.SetDefaultScaffolderCmdlet

"Operação não disponível" is "Operation unavailable" in portuguese.

**Comment by processedbeets** [comment]
Hi,

Thanks for updating me. I've just installed Visual Studio 2013 Update 5 locally and I've seen there appears to be an issue when trying to install the package so I'll take a look tonight.

As an aside, is there anything preventing you from upgrading to Visual Studio 2015?

Thanks.

**Comment by cigano** [comment]
Hi David, 

There was a bug in VS2015 (I don't remember in details) that made me keep VS2013 for a while, but I can use VS2015 as long as you work on the issue. My concern is just maintain the best compatibility possible.

**Comment by processedbeets** [comment]
Hi,

I've uploaded a new version of all 3 packages. I rebuilt the projects for .Net 4.5 and used Microsoft.VisualStudio.Shell.12.0 instead of 14.0.

I've tested this on both 2013 & 2015 and it appears to function correctly on both.

Please give it a go and confirm with me when you get a chance.

Thanks,
David.

**Comment by cigano** [comment]
Hi David, 

I've reinstalled all the 3 packages, cleaned the solution, closed VS2013 and reopened it, and it works! Congratulations!

Thanks a lot for your effort. Now your package is VS2013 compatible.

**Comment by processedbeets** [comment]
Great. Thank's for your help with this. Cheers, David.
