### ISSUE TITLE
Does this still work in VS2017 with EF6?

### ISSUE THREAD

**Issue by beck8** [processedbeets/ASP.NET-MVC-Scaffolding#4]
I cannot get this to work in an MVC ASP.NET with EF6 project sample in Visual Studio 2017. I tried updating all packages, but maybe that is the problem? 

Or is there a replacement now? I know the dotnet command-line tools (.NET Core CLI) only work for Entity Core and I have no problems using the UI for "Add->Controller" in VS with EF6. Is there no way to automate that from the command-line? I'm not quite ready to move to Entity Core.

**Comment by processedbeets** [comment]
Hi. Thanks for getting in touch. There is currently no support for 2017 but
if you'd like to make a pull request I'd be happy to merge in a fix. If you
look at the last commits you'll see what needs changed.

Cheers,
David.

**Comment by cigano** [comment]
David, 

What about changing the NuGet Package to MvcScaffolding.VS2017 and offer backwards compatibility to Visual Studio 2015?

If you agree, I can do the modifications here.

**Comment by processedbeets** [comment]
Hi,

Yes, that sounds reasonable. Feel free to make the changes and I can pull them in. 

Thanks you 😊

**Comment by cigano** [comment]
David, 

I don't remember how to debug the package. Can you refresh my mind, please?

Thanks.

**Comment by processedbeets** [comment]
Hi,

I’m not sure I ever reached a satisfactory method for debugging. It is possible by attaching to a process.

You could always make use of a line like the following wrapped round your code:
while (!System.Diagnostics.Debugger.IsAttached){ }

Oleg’s stuff is usually pretty good when it comes to T4 Templating:
http://olegsych.com/T4Toolbox/tutorial/troubleshooting-code-generation-errors.html

Or you could try here:
http://huqingyu.com/blog/2014/01/799.htm

Sorry I can’t be more direct use, I’ve not looked at this in over 2 years and no longer have the environment setup to support it.

Good luck. Let me know how you get on.

Thanks,
David.

**Comment by cigano** [comment]
Published the updates here:

 - [T4Scaffolding.Core.VS2017](https://www.nuget.org/packages/T4Scaffolding.Core.VS2017/) 
 - [T4Scaffolding.VS2017](https://www.nuget.org/packages/T4Scaffolding.VS2017/)
 - [MvcScaffolding.VS2017](https://www.nuget.org/packages/MvcScaffolding.VS2017/)
