### ISSUE TITLE
Unable to find type [NuGet.PackageManager].

### ISSUE THREAD

**Issue by pablotdv** [processedbeets/ASP.NET-MVC-Scaffolding#7]
Every time I open the project, I have the following error.

```
Unable to find type [NuGet.PackageManager].
At D:\Projetos\Syns\Syns\packages\T4Scaffolding.Core.VS2017.1.0.0\tools\init.ps1:4 char:5
+ if ([NuGet.PackageManager].Assembly.GetName().Version -lt 1.4)
+     ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (NuGet.PackageManager:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
```

**Comment by processedbeets** [comment]
@cigano Does this look like anything you experienced when upgrading to VS2017?

**Comment by cigano** [comment]
Apparently the identifier was removed from DTE in this version. I'll update the package in the weekend, removing the verification.

**Comment by pablotdv** [comment]
Thanks @cigano, you are the man

**Comment by cigano** [comment]
Solved. [See version 1.0.1](https://www.nuget.org/packages/T4Scaffolding.Core.VS2017/1.0.1). 

This issue can be closed.

**Comment by processedbeets** [comment]
Thanks for your work on this @cigano

**Comment by cigano** [comment]
@processedbeets Can you please close this issue? It is already solved.

**Comment by BryanCrow** [comment]
It's solved with T4Scaffolding.Core.VS2017 1.0.1, but the current version of T4Scaffolding.VS2017 still only requires 1.0.0, so by default people are still getting the old 1.0.0 version with this bug still present. Please update T4Scaffolding.VS2017's dependencies on T4Scaffolding.Core.VS2017 to >= 1.0.1 before closing.

**Comment by Jameskmonger** [comment]
`T4Scaffolding.VS2017` still has a dependency on `T4Scaffolding..Core.VS2017` version `1.0.0`.

Can @BryanTheCrow 's fix be merged and published? If not, how can I manage my local dependencies to stop me from getting the VS2017 issue?

**Comment by processedbeets** [comment]
Hi @Jameskmonger apologies for the delayed response here, I've not had the time to be maintaining this repo. Thanks to @BryanTheCrow for providing the fix. I've now merged this. Please grab the latest.

**Comment by cigano** [comment]
@BryanTheCrow I got your modifications, but it's good to say that, in order to enforce an update at NuGet, you should be changing the library version number at the .nuspec file as well.

@processedbeets, gonna need your help again to merge modifications that I'll do to publish the package at nuget.org.

**Comment by processedbeets** [comment]
No problem. Happy to merge any changes.

Thanks so much for your help.

Cheers,
David.
